name: Write to json

on:
  push:
    branches: [ "develop" ]

  workflow_dispatch:

env: 
  REACT_APP_GIT_VERSION: ${{ secrets.REACT_APP_GIT_VERSION}}

jobs:
  # This workflow contains a single job called "build"
  create-envfile:
 
    runs-on: ubuntu-latest
 
    steps:
    - name: Make envfile
      uses: SpicyPizza/create-envfile@v1.3
      with:
        envkey_DEBUG: false
        envkey_SOME_API_KEY: "123456abcdef"
        envkey_REACT_APP_GIT_VERSION: ${{ secrets.REACT_APP_GIT_VERSION }}
        envkey_10_A_NUMBERED_KEY: "lorem"
        envkey_3_ANOTHER_NUMBERED_KEY: "ipsum"
        envkey_5_NUMBERED_KEY_VALUE_WITH_SPACES: "lorem ipsum"
        envkey_1_ONE_MORE_NUMBERED_KEY: true
        some_other_variable: foobar
        file_name: .env
        fail_on_empty: false

  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: env-demo

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 18
          cache: npm

      - name: Install dependencies
        run: |
          npm ci
          npm run git-info
          npm run build

      - name: Git describe
        id: ghd
        uses: proudust/gh-describe@v1.5.4
      - name: Check outputs
        run: |
          echo "describe: ${{ steps.ghd.outputs.describe }}"
          echo "tag     : ${{ steps.ghd.outputs.tag }}"
          echo "distance: ${{ steps.ghd.outputs.distance }}"
          echo "sha     : ${{ steps.ghd.outputs.sha }}"

      - name: Set Git tag
        run: |
          echo "tag=${{ steps.ghd.outputs.tag }}" >> $GITHUB_ENV
          echo "build_date=$(date +'%Y-%m-%d-%H:%M')" >> $GITHUB_ENV
          echo "git_tag_date=$(git log -1 --format=%ai --date=short)" >> $GITHUB_ENV
      - name: Check output
        run: |
          touch ${{ github.workspace }}/env-demo/src/.env
          echo ${{env.tag}} - ${{env.build_date}} - ${{env.git_tag_date}}
          echo $REACT_APP_GIT_VERSION=${{env.tag}} - ${{env.git_tag_date}} >> .env

      - name: Create .env file
        uses: ozaytsev86/create-env-file@v1
        with:
          ENV_TEST_API_KEY: ${{ secrets.TEST_API_KEY }}
          ENV_ANOTHER_KEY: ${{ secrets.ANOTHER_KEY }}
      
      - name: Run git script
        uses: actions/github-script@v6
        with:
          script: |
            const { default: printGitTag } = import(${{ github.workspace }}/env-demo/src/gitTagInfo.js)
            const { default: printStuff } = await import(${{ github.workspace }}/env-demo/src/print-stuff.js)
            console.log('stuff')
            await printStuff()
            printGitTag(${{env.tag}})
            
