name: Write to json

on:
  push:
    branches: [ "develop" ]

  workflow_dispatch:

jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./env-demo

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 16
          cache: npm

      - name: Install dependencies
        run: npm ci

      - name: Git describe
        id: ghd
        uses: proudust/gh-describe@v1
      - name: Check outputs
        run: |
          echo "describe: ${{ steps.ghd.outputs.describe }}"
          echo "tag     : ${{ steps.ghd.outputs.tag }}"
          echo "distance: ${{ steps.ghd.outputs.distance }}"
          echo "sha     : ${{ steps.ghd.outputs.sha }}"

      - name: Set Git tag
        id: vars
        run: |
          echo "tag=$(git describe --tags --abbrev=0)" >> $GITHUB_ENV
          echo "build_date=$(date +'%Y-%m-%d-%H:%M')" >> $GITHUB_ENV
          echo "git_tag_date=$(git log -1 --format=%ai --date=short ${{env.tag}})" >> $GITHUB_ENV
      - name: Check output
        run: echo ${{env.tag}} - ${{env.build_date}} - ${{env.git_tag_date}}
      
      - name: Run git script
        uses: actions/github-script@v6
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            const { default: printGitTag } = await import('${{ github.workspace }}/env-demo/src/gitTagInfo.js')
            await printGitTag({github, context, core})
