name: Write to json

on:
  push:
    branches: [ "develop" ]

  workflow_dispatch:

jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3
      - uses: actions/github-script@v6
      - name: Create and populate json file
        with:
          script: |
            const { default: printGitTag } = await import('${{ github.workspace }}/src/gitInfo.ts')

            await printGitTag()
