name: Write to json

on:
  push:
    branches: [ "develop" ]

  workflow_dispatch:

jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./env-demo

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3
      - uses: actions/github-script@v6
      - uses: actions/setup-node@v3

      - name: Install dependencies
        run: npm ci  
        with:
          cache: npm
          node-version: "v14.17.6"
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            const script = require('./src/gitTagInfo.js')
            console.log(script())
