name: Write to json

on:
  push:
    branches: [ "develop" ]

  workflow_dispatch:

jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3
      - uses: actions/github-script@v6
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            const execSyncWrapper = (command) => {
              let output = null;
              try {
                output = execSync(command).toString().trim().split(/\r?\n/);
              } catch (error) {
              console.error(error);
              }
              return output;
            }
            
            const main = () => {
              let gitTag = execSyncWrapper("git describe --tags --abbrev=0");
              let gitTagWithDate = execSyncWrapper(`git log -1 --format=%ai --date=short ${gitTag}`);

              const obj = {
                gitTag,
                gitTagWithDate
              };

              const filePath = path.resolve('env-demo/src', 'gitTagVersion.json');
              const fileContents = JSON.stringify(obj);

              fs.writeFileSync(filePath, fileContents);
              console.log(`Wrote the following contents to ${filePath}${fileContents}`);
            }

            main();
